name: Build Electron App

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build:ts

      - name: Rebuild native modules
        run: npx electron-builder install-app-deps
      - name: Create .env
        run: |
          echo "TMDB_KEY=${{ secrets.TMDB_KEY }}" > .env
      - name: Build Linux
        env:
          NODE_ENV: production
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx electron-builder --linux AppImage --publish always
  build-windows:
    name: Build Windows (NSIS)
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build:ts

      - name: Rebuild native modules
        run: npx electron-builder install-app-deps
      - name: Create .env
        run: |
          echo "TMDB_KEY=${{ secrets.TMDB_KEY }}" > .env
      - name: Build Windows
        env:
          NODE_ENV: production
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx electron-builder --win nsis --publish always
